### ISSUE TITLE
Use public url in .gitmodules

### ISSUE THREAD

**Issue by schnaader** [dropbox/avrecode#1]
Using the commands from README.md on an Ubuntu machine, I get the following error when trying to do `git submodule update --init`:

```
Permission denied (publickey).
fatal: Could not read from remote repository.
```

According to [this answer on StackOverflow](http://stackoverflow.com/questions/8197089/fatal-error-when-updating-submodule-using-git), the public URL has to be used, and indeed it works after changing the `url = ...` line in .gitmodules to 

`url = https://github.com/dropbox/libavcodec-hooks.git`

 and calling `git submodule sync`.

I'm not sure if this is a general problem, but if it is, please change .gitmodules accordingly.

**Comment by lesniewski** [comment]
Done. Thanks for the report - I think everyone who's built the project so far has had ssh access to github, so we didn't notice.
